# Numpy Lil Guide

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

<ul>
<li>NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
</li>

<li>The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
</li>
    
<li>NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.</li>
    


<li>A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.
</li>
</ul>

In [2]:
import numpy as np #Need to import Numpy

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [4]:
arrayMultiD = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrayMultiD)
print()
print("*" * 50)
print("The first element of the first array is: {}".format(arrayMultiD[0][0]))
print("The second element of the first array is: {}".format(arrayMultiD[0][1]))
print("*" * 50)
print("The first element of the second array is: {}".format(arrayMultiD[1][0]))
print("The second element of the second array is: {}".format(arrayMultiD[1][1]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

**************************************************
The first element of the first array is: 1
The second element of the first array is: 2
**************************************************
The first element of the second array is: 5
The second element of the second array is: 6


## More info about arrays
This section will cover the creation of **1D Array**, **2D Array**, **ndarray**, **vectors**, **matrices**

You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

In [5]:
# Create an array of zeros

zeroA = np.zeros(2)
zeroB = np.zeros([3,3])

print(zeroA)
print("-" * 20)
print(zeroB)

[0. 0.]
--------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
ones1 = np.ones(2)
ones2 = np.ones([3, 3])

print(ones1)
print("-" * 20)
print(ones2)

[1. 1.]
--------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


The function **empty** creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards

In [7]:
# Create an empty array with two elements

np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Create an array with elements within a range

np.arange(4)


array([0, 1, 2, 3])

An array that contains a range of evenly spaced intervals can be created by usingfirst number, last number, and the step size

In [9]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

I can also use np.linspace() to create an array with values that are spaced linearly in a specified interval

In [10]:
np.linspace(2, 10, num = 5)

array([ 2.,  4.,  6.,  8., 10.])

### Specify data type

While the default data type is floating point (np.float64), I can explicitly specify which data type you want using the dtype keyword.



In [11]:
x = np.ones(2, dtype = np.int64)
x

array([1, 1])

In [12]:
type(x.dtype)

numpy.dtype[int64]

### Adding, removing, and sorting elements

This section covers **np.sort()**, **np.concatenate()**

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [13]:
unOrderedArr = np.array([1, 5, 7, 8, 9, 4, 3])

In [14]:
orderedArr = np.sort(unOrderedArr)  
print(orderedArr)

[1 3 4 5 7 8 9]


In addition to sort, which returns a sorted copy of an array, you can use:
<ul>

<li>argsort, which is an indirect sort along a specified axis,</li>

<li>lexsort, which is an indirect stable sort on multiple keys, </li>

<li>searchsorted, which will find elements in a sorted array, and </li>

<li>partition, which is a partial sort.</li>

</ul>

### Concatenate function

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [16]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [18]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.concatenate((x, y), axis=0) #axis is to indicate which axis you want to concatenate along

array([[1, 2],
       [3, 4],
       [5, 6]])

[Link to full guide]("https://numpy.org/doc/stable/user/absolute_beginners.html")

In [22]:
a = ("red", "green", "blue")
b = ("a", "b", "c")

c = list(zip(a, b))

In [23]:
c

[('red', 'a'), ('green', 'b'), ('blue', 'c')]